# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python versions
python:
   - "3.6"
   - "3.7"
   - "3.8"

# set the operating systems to be tested

os:
   - linux

install:
   - pip install -r requirements.txt
   - pip install -r test-requirements.txt

script:
   - python setup.py develop
   - py.test


