# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.8, 3.9]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up conda env ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: geonum
        environment_file: geonum_env.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
    - name: Conda info
      run: |
        conda --version
        which python
    - name: Display current environments
      run: conda info --envs
    - name: Install test dependencies
      run: |
        conda install -c conda-forge --file ./test-requirements.txt
    - name: Install geonum
      run: python ./setup.py install
    - name: Run pytest
      run: pytest --cov=geonum/ --cov-report xml
    - name: Upload coverage to Codecov (Python 3.9, Ubuntu)
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9'
      uses: codecov/codecov-action@v1
      with:
          file: ./coverage.xml
          flags: unittests
    - name: Run example scripts
      run: |
        python scripts/ex1_basic_objects.py
        python scripts/ex2_geosetup_intro.py
        python scripts/ex4_elevation_profiles.py
        python scripts/ex5_topodata.py