# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: CI

on: [pull_request]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0} # https://github.com/conda-incubator/setup-miniconda#important
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up conda env ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        environment-file: geonum_env.yml
        activate-environment: geonum
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
    - name: Conda info
      run: conda info
    - name: Python version
      run: which python
    - name: Display current environments
      run: conda info --envs
    - name: Install test dependencies
      run: |
        conda install -c conda-forge --file ./test-requirements.txt
    - name: Install newest version of pip/setuptools
      run: python -m pip install --upgrade pip setuptools
    - name: Install geonum
      run: python -m pip install ./
    - name: Run pytest
      run: pytest test --cov=geonum/ --cov-report xml
    - name: Upload coverage to Codecov
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9'
      uses: codecov/codecov-action@v1
      with:
          file: ./coverage.xml
          flags: unittests
    - name: Run example scripts
      run: |
        python scripts/ex1_basic_objects.py
        python scripts/ex2_geosetup_intro.py
        python scripts/ex4_elevation_profiles.py
        python scripts/ex5_topodata.py
