name: Publish to Test PyPI
on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.9

        - name: Install dependencies
          run: | 
            python -m pip install --upgrade pip
            pip install wheel twine build           

        - name: Print release version
          run: echo "Release version is $GITHUB_REF_NAME"

        - name: Build package
          run: python -m build

        - name: Print content of dist folder
          run: ls dist

        - name: Check package
          run: twine check dist/*

        - name: Publish package
          env:
            TWINE_USERNAME: __token__
            TWINE_PASSWORD: ${{ secrets.TESTPYPI_API_TOKEN }}
          run: twine upload --repository testpypi dist/*