name: Publish to PyPI
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.9
        - name: Install dependencies
          run: pip install wheel twine
        - name: Set release version as ENVVAR
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        - name: Print release version
          run: |
            echo $RELEASE_VERSION
            python -c "import os; print(os.environ['RELEASE_VERSION'])"
        - name: Print GITHUB_REF_NAME
          run: echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
        - name: Build package
          run: python setup.py sdist bdist_wheel
        - name: Print content of dist folder
          run: ls dist