name: Publish to PyPI
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.9
        - name: Install dependencies
          run: pip install wheel twine
        - name: Print release version
          run: |
            echo "Release version is: $GITHUB_REF_NAME"
        - name: Build package
          run: python setup.py sdist bdist_wheel
        - name: Print content of dist folder
          run: ls dist
        - name: SUBSET
          run: ls dist/*${GITHUB_REF_NAME}*
        - name: Publish package
          env:
            TWINE_USERNAME: __token__
            TWINE_PASSWORD: ${{ secrets.TESTPYPI_API_TOKEN }}
          run: |
            twine check dist/*
            twine upload --repository testpypi dist/*${GITHUB_REF_NAME}*