name: Github Release
on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the latest release tag
        id: latest-release
        run: |
          LATEST_RELEASE=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r '.tag_name')
          echo "${LATEST_RELEASE}"
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV

      - name: Get commit branch
        run: |
          COMMIT_BRANCH="${GITHUB_REF#refs/heads/}"
          echo "${COMMIT_BRANCH}"
          echo "COMMIT_BRANCH=$COMMIT_BRANCH" >> $GITHUB_ENV

      - name: Make draft release
        run: |
          echo ${COMMIT_BRANCH}
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d '{"tag_name":"v1.5.0","name":"TEST RELEASE","body":"Description of the release","draft":true,"prerelease":false,"generate_release_notes":false}'