name: Github Release
on: push

jobs:
  release_github:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Get the latest release tag
          id: latest-release
          run: |
            LATEST_RELEASE=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r '.tag_name')
            echo "${LATEST_RELEASE}"

        - name: Print current REF
          run: echo "Release version is $GITHUB_REF_NAME"
