name: Github Release
run-name: ${{ github.actor }} is running this
on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Release Draft
        id: create_release
        uses: actions/github-script@v6
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            try {
            
              const response = await github.repos.createRelease({
                owner: context.repo.owner,
                generate_release_notes: true,
                repo: context.repo.repo,
                tag_name: v1.5.0.dev11,
                name: TEST,
                draft: true
              });
              console.log(response.data);
            } catch (error) {
              core.setFailed(error.message)
            }