name: Github Release
on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the latest release tag
        run: |
          LATEST_RELEASE=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r '.tag_name')
          echo "${LATEST_RELEASE}"
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV

      - name: Make draft release
        id: make-release
        run: |
          RELEASE_JSON=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d '{
              "tag_name":"v1.5.0test7",
              "name":"TEST RELEASE",
              "body":"Description of the release",
              "draft":true,
              "prerelease":true,
              "generate_release_notes":false}')
          RELEASE_ID=$(echo $RELEASE_JSON | jq -r '.id')
          echo "Release ID: ${LATEST_RELEASE}"
          echo "RELEASE_ID=$RELEASE_ID" >> $GITHUB_ENV

      - name: Create release notes
        id: release_notes
        run: |
          RELEASE_NOTES=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases/generate-notes \
            -d '{
              "tag_name":"v1.5.0",
              "previous_tag_name":"v1.4.4"}'\
            | jq -r '.body')
          
          echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV

      - name: Update release with autogenerated notes
        run: |
          RELEASE_ID="${{ env.RELEASE_ID }}"
          RELEASE_NOTES="${{ env.RELEASE_NOTES }}"
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID \
            -d '{
              "body":"'"$RELEASE_NOTES"'"}'

